### PR TITLE
Add concurrency limiter

### PR DESCRIPTION
**Pull request by sargun**
This adds / moves the concurrency limiter code (verbatim) from https://github.com/openfaas-incubator/of-watchdog.

### CODE REVIEW

**Comment by sargun** [comment]
@alexellis Do you want to enable travis on this project?

**Comment by alexellis** [comment]
Hi,

Thank you for this pull request 

Please create an issue for Travis and for Derek.

Because Derek isn't running here yet he didn't mention that you need to sign off the commit you made. `git commit --amend -s` should do it followed by a force push. 

Alex

**Comment by sargun** [comment]
✅

**Review by alexellis — APPROVED** [review]
LGTM

**Comment by alexellis** [comment]
Thank you!

**Pull request merged**
